### ISSUE TITLE
Add composer.json support

### ISSUE THREAD

**Issue by ewinslow** [iionly/tidypics#16]
Would be cool to have tidypics support composer-based installs.

**Comment by iionly** [comment]
I've no idea what would be necessary to achieve that. The only thing I've managed with composer so far is getting the dependencies for Elgg 1.10 installed on a test installation.

**Comment by ewinslow** [comment]
Lots of docs at getcomposer.org. Also you can search packagist for existing elgg plugins with support.

Will have to write some docs for learn.elgg.org

**Comment by serega3000** [comment]
Hello! Composer is very useful tool to install elgg with all modules and update them using command line. This is must have thing in your very cool module.
To add composer support in your module, please:
1. Confirm my pull request
2. Login to packagist.org using your github account
3. Click "submit package"
4. Fill url of your project (https://github.com/iionly/tidypics)
5. goto https://packagist.org/profile/
6. Click to "show api token". Copy token to clipboard.
7. Goto https://github.com/iionly/tidypics/settings/hooks
8. CLick "add service" and find "packagist" in list.
9. Fill user - "iionly", api token - token from clipboard. Field "domain" leave blank.
Its all!
Webhook required to update your project versions automatically in composer

**Comment by iionly** [comment]
@serega3000 Thanks. I will look into the composer support soon when I have some time to spare (maybe next weekend).

**Comment by iionly** [comment]
@serega3000 Thanks. I've merged your PR. I've added some more stuff to composer.json that seemed to make sense.

@ewinslow MIght be nice to get some feedback if the composer-based install of Tidypics works now. I don't need this service myself, so I will likely not give it much attention.

**Comment by ewinslow** [comment]
@iionly - FYI I'm going to try to get the elgg project on general to be more composer-managed since it's so much easier than downloading and unzipping by hand, as we must do now.
