### ISSUE TITLE
Remove upload  limitation of 10 images to be uploaded in one batch (Elgg 1.9.x)

### ISSUE THREAD

**Issue by rohit1290** [iionly/tidypics#19]
How to remove the limitation of 10 images to be uploaded in one batch when using Plupload HTML5/HTML4 uploader.?

**Comment by iionly** [comment]
It would be necessary to modify tidypics/views/default/js/photos/uploading.php.

You can either just increase $max_files to have a higher limit.

Or you can completely remove the callbacks for the FilesAdded and FilesRemoved events. Then the number of files in the queue wouldn't get checked at all and therefore the limit would be not used.
