### ISSUE TITLE
Page numbers not displaying properly

### ISSUE THREAD

**Issue by Westlake56** [iionly/tidypics#20]
I'm running Elgg 1.11.1 with Tidy Pics 1.10.6. I've tried clearing the cache.

Where page 6 and 7 would be it just has a blank box for page six and no box for page seven. If you click "Next" it just repeats instead of showing 9, 10, 11 etc.

![photos page number](https://cloud.githubusercontent.com/assets/11148775/7487981/824da37c-f390-11e4-96b5-8e68a91584b1.png)

**Comment by iionly** [comment]
The pagination bar in your image looks right to me though. If you look closely, the 6th box is not empty but contains "...". This is normal (and the pagination bar is provided by Elgg core anyway). If you are on page 1, this is how the pagination bar will look like: it should show entries for the first five page, then a placeholder ("...") showing that there are more page left out and then the last page (which would be page 8 in your case?). If you select for example page 4 or 5 directly, you will see pages 6 and 7 (with the first entry always being the first page and the last entry should be the last page).

The "Previous" and "Next" buttons will also not result in display of the next bunch of pages but only load the next or previous page in relation to the page you are currently viewing. If you would be for example on page 1, the "Next" button will load page 2 and on page 2 the "Previous" button will load page 1 again.

To be honest, I'm not fully happy with the way the pagination works on Elgg, too. I had suggested some improvements (https://github.com/Elgg/Elgg/issues/5055) like some additional buttons to jump over more than a single page (e.g. -10 / -5 / +5 / +10) but this wasn't seen as being useful to be implemented in Elgg core.

So, I believe everything is working as intended. If you think I'm wrong, you could open the issue again.

**Comment by Westlake56** [comment]
Hello,

Thank you for the explanation. I agree with you, I think the pagination 
bar can be done better. I've never seen it done that way before which is 
why I thought it was a bug.

Regards,
Dan

On 5/06/15 2:40 PM, iionly wrote:
>
> The pagination bar in your image looks right to me though. If you look 
> closely, the 6th box is not empty but contains "...". This is normal 
> (and the pagination bar is provided by Elgg core anyway). If you are 
> on page 1, this is how the pagination bar will look like: it should 
> show entries for the first five page, then a placeholder ("...") 
> showing that there are more page left out and then the last page 
> (which would be page 8 in your case?). If you select for example page 
> 4 or 5 directly, you will see pages 6 and 7 (with the first entry 
> always being the first page and the last entry should be the last page).
>
> The "Previous" and "Next" buttons will also not result in display of 
> the next bunch of pages but only load the next or previous page in 
> relation to the page you are currently viewing. If you would be for 
> example on page 1, the "Next" button will load page 2 and on page 2 
> the "Previous" button will load page 1 again.
>
> To be honest, I'm not fully happy with the way the pagination works on 
> Elgg, too. I had suggested some improvements (Elgg/Elgg#5055 
> <https://github.com/Elgg/Elgg/issues/5055>) like some additional 
> buttons to jump over more than a single page (e.g. -10 / -5 / +5 / 
> +10) but this wasn't seen as being useful to be implemented in Elgg core.
>
> So, I believe everything is working as intended. If you think I'm 
> wrong, you could open the issue again.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/iionly/tidypics/issues/20#issuecomment-99568172>.
>

-- 

BITS Of Knowledge
796 Dundalk Dr.
London, ON N6C 3V2

519-681-2555

http://www.bitsofknowledge.com

Everything For Seniors Directory - Phone: 519-681-2555
http://everythingforseniorsdirectory.ca 
<http://everythingforseniorsdirectory.ca/>

CONFIDENTIALITY NOTICE: This email including any attachments may contain 
confidential or proprietary information. All information contained 
herein is for the exclusive and confidential use of the intended 
recipient. If you are not the intended recipient, please do not read, 
distribute or take action in reliance upon this message. Any 
distribution, copying, use, disclosure or dissemination of this 
information is unauthorized, strictly prohibited, and may be illegal. If 
you have received this message in error, please notify the sender 
immediately and promptly destroy this message and its attachments 
including any copies.
