### ISSUE TITLE
Help! Tidy stopped working after a year.

### ISSUE THREAD

**Issue by BigManZP** [iionly/tidypics#21]
Tidy stopped working after a year. Don`t show images and thumbnails. Files are uploaded to the server fine. But they are not seen. Permission 777 / GD library. Screenshot: http://awesomescreenshot.com/0aa5civd2d and http://awesomescreenshot.com/0785civh57
Sorry for my english :-) Please, really need your help. Thanks

**Comment by iionly** [comment]
Please don't ask for user support on github. This is what the Elgg community site is for. The github site is for reporting bugs or issues that are caused by something within the code of a program / plugin and not if something is wrong on your server.

**Comment by iionly** [comment]
And in case you updated Elgg core or a plugin before Tidypics stopped working or if you moved to another server this could also be the reason why Tidypics no longer shows the images. Or you might check if any of the other 3rd party plugins used on your site is causing the problem (temporarily disable them). When opening a thread at the Elgg community for further support you should include more info about what you have changed recently that possibly could cause the problem.

**Comment by BigManZP** [comment]
Thanks and sorry)) You can delete issue :-)
