### ISSUE TITLE
Error in admin settings 

### ISSUE THREAD

**Issue by tempest-kitty** [iionly/tidypics#26]
when viewing the settings for this plugin in elgg 2.0 clicking on "Server configuration" and "Help" give a fatal error page. 

`elgg:markdown is not a registered library

InvalidParameterException Object
(
[message:protected] => elgg:markdown is not a registered library
[string:Exception:private] => exception 'InvalidParameterException' with message 'elgg:markdown is not a registered library'`

**Comment by iionly** [comment]
Thanks for reporting.

Fixed by https://github.com/iionly/tidypics/commit/35dc88ebee2315a728b38ce1f6454c1e4878464b.
