### ISSUE TITLE
elgg_load_js('tidypics') does not always result in file being loaded?!

### ISSUE THREAD

**Issue by propertunist** [iionly/tidypics#28]
i just added a feature to my site where the profile image on the profile pages loads in a lightbox when clicked. i used the tidypics approach to images/lightboxes to do this, but found that on my production server, the JS file fails to be loaded in the page footer (or at all) and so the feature fails.
on my development server this works fine.
i have done some surface digging but haven't found a cause for this yet. it may be that this is nothing to do with tidypics code, but at present tidypics is my starting point.

**Comment by propertunist** [comment]
n.b. i am using 1.12.10 elgg and the latest tidypics.

**Comment by iionly** [comment]
Tidypics now uses AMD modules for all its JS code. Therefore, elgg_load_js() will no longer work. Use elgg_require_js() instead. For example elgg_load_js('tidypics') is to be replaced with elgg_require_js('tidypics/tidypics').
