### ISSUE TITLE
"Photos you're tagged in" doesn't work

### ISSUE THREAD

**Issue by joalbor1** [iionly/tidypics#29]
The menu option "Photos you're tagged in" doesn't work. I have found that in the '/views/default/resources/tidypics/photos/tagged.php' file is not coming as a parameter the ID of the user logged in, so this function is not showing anything when it should show the photos where you're tagged in.

**Comment by iionly** [comment]
Thanks for reporting. When updating Tidypics for Elgg 2.0 I failed to update the code for this page correctly. I'll try to fix it soon.

**Comment by iionly** [comment]
Fixed by https://github.com/iionly/tidypics/commit/421e359673ec6a147d044d789aea34bb6e00d199.
