### ISSUE TITLE
eregi_replace is not compatible with PHP7

### ISSUE THREAD

**Issue by propertunist** [iionly/tidypics#31]
i just found that the function eregi_replace is called in classes/tidypicsAlbum.php and it has been dropped from PHP7. it appears the solution is to just use preg_replace with the same parameters instead.

**Comment by iionly** [comment]
Thanks for reporting. Have you found other issues with php7? How are you testing?

I'll have it fixed in the next release.

**Comment by propertunist** [comment]
you're welcome! most of the issues i found were in coldtrick's plugins and ismayil's - there weren't many though.. no big deal.

**Comment by iionly** [comment]
Fixed by https://github.com/iionly/tidypics/commit/aa61471ff9d14baa1b50a14cc32b6a1a339206f9.
