### ISSUE TITLE
subtype is not being checked for photo views, causing errors

### ISSUE THREAD

**Issue by propertunist** [iionly/tidypics#32]
if a user attempts to view a photo using a guid that is for a different type of elgg entity (e.g. a blog) - which occurred on my site for unknown reasons - the outcome is that they will see a fatal error.
the subtype needs to be checked to ensure it is a tidypics image in file: /resources/tidypics/photos/image/view.php
```
if ((!$photo)||(!elgg_instanceof($photo, 'tidypicsImage'))) {
```

**Comment by propertunist** [comment]
correction, that needs to be:
```
if ((!$photo)||(!elgg_instanceof($photo, 'object','image'))) {
```

**Comment by iionly** [comment]
Yes. Thanks for reporting. I'll make a PR soon. But before doing so I want to check other views for the same kind of issue and then make a PR that fixes it in all views.

**Comment by iionly** [comment]
Fixed by https://github.com/iionly/tidypics/commit/d902f4b5eb0f6d28a11eab35f9a7a642245be381.
