### ISSUE TITLE
Group Widget "Latest Photos": option to add photos overwrites gallery output

### ISSUE THREAD

**Issue by Pasley70** [iionly/tidypics#37]
See /views/default/widgets/groups_latest_photos/content.php
Line 40

`$image_html = elgg_view('output/url', array(`

Maybe better:

`$image_html .= elgg_view('output/url', array(`

or if you do not want to add this link when photos available, check if $image_html have content.

**Comment by iionly** [comment]
It should be .= instead of = indeed. The . seems to have gone lost in the latest 2.3.3 release. I need to fix it in the next release for sure. I just have to decide if I get more done for Tidypics soon or if I make a new release with just this tiny fix.

**Comment by iionly** [comment]
Fixed by https://github.com/iionly/tidypics/commit/ef0316a49ec22064b6370aceb05e631f73792196.
