### ISSUE TITLE
TidyPicsImage::delete() on PHP 7.2

### ISSUE THREAD

**Issue by jdalsem** [iionly/tidypics#38]
Fatal error: Declaration of TidypicsImage::delete() must be compatible with ElggFile::delete($follow_symlinks = true)

**Comment by jdalsem** [comment]
same for album

**Comment by iionly** [comment]
Fixed by https://github.com/iionly/tidypics/commit/a0fb3c8dff2a172bb8cd4e54ac80b737fd5d090e.
