### ISSUE TITLE
download photo comes in resize not in original

### ISSUE THREAD

**Issue by dipenpatel235** [iionly/tidypics#40]
hello..
i have upload pic of 1MB but when i am downloading that same pic then it is comes in approx 170Kb 
so is your plugin is resizing pic after upload or upload time ?

can i get same as original ?
what change i required to do in plugin ?

Thanks
Dipen

**Comment by iionly** [comment]
If you have NOT enabled the Tidypics plugin option "Image size/resolution reduction on client-side before upload", the original image file will get saved on image upload and should be available for download if you either click on the "Download photo" button or save the image file displayed in the image popup. The image file displayed when viewing a single photo (not in the popup) is not the original image file though (but the large thumbnail version of it).
