### ISSUE TITLE
hide Most View 

### ISSUE THREAD

**Issue by dipenpatel235** [iionly/tidypics#42]
hello..
i have lots of most view filter.
how can we hide all option.

see below screenshot
https://i.imgur.com/ONToQka.png

**Comment by iionly** [comment]
Menu entries are registered in /mod/tidypics/views/default/photos/sidebar/extended_menu.php. Just comment out the entries that you don't want.

Please, post on the Elgg community site for questions not related to actual bugs in Tidypics. The github repo is first of all for development only.

**Comment by dipenpatel235** [comment]
Ok..thanks
