### ISSUE TITLE
tidypics plus not working with tidypics 2.3.4

### ISSUE THREAD

**Issue by HerbWalsh** [iionly/tidypics#45]
i have just installed v2.3.4 and now the "Mine or friends" photos don't show in photos but if i deactivate tidypics plus everything works again but without the plus actions obviously. I realize plus was never released as a version but it has been working thus far

**Comment by iionly** [comment]
For Tidypics 2.3.4 large parts of code have been rewritten and cleaned-up to get a better consistency in code and user experience (forms and other pages layout, popups and slideshow etc.) and also to make use of Elgg core API functions newly introduced in Elgg 2.3 (again for consistency and also to some extend as preparation to reduce the work necessary for a future version compatible with Elgg 3.0). These changes broke backward compatibility and therefore it's unfortunately necessary to update the Tidypics Plus plugin accordingly to be compatible with Tidypics 2.3.4. I'm afraid it's nothing I could do from the Tidypics-side to fix that. Please ask @propertunist if he could release an updated version of Tidpics Plus.

**Comment by HerbWalsh** [comment]
thanx for the quick response..I messaged him with the request to update..
