### ISSUE TITLE
in Elgg 4.0 error: TidypicsAlbum::save() must be compatible with ElggEntity::save(): bool 

### ISSUE THREAD

**Issue by maxvergelli** [iionly/tidypics#55]
I installed a fresh Elgg 4.0 (without other external plugins, but only the bundled plugins with the version 4.0)
and when I activate Tidypics from Plugins I got this error from the server

[error] [client ] - www.pantabook.com - AH01215: PHP Fatal error: Declaration of TidypicsAlbum::save() must be compatible with ElggEntity::save(): bool in /web/htdocs/www.******.com/home/mod/tidypics/classes/TidypicsAlbum.php on line 43: /web/htdocs/www.******.com/home/index.php

**Comment by iionly** [comment]
Tidypics is not ready for Elgg 4 yet. I've not even started working on an updated version. This error is very likely not the only one that needs to be fixed for Tidypics to run on Elgg 4. So, for the time being, if you need Tidypics, please use Elgg 3.

**Comment by iionly** [comment]
Fixed in version 4.0.0 of Tidypics (https://github.com/iionly/tidypics/releases/tag/4.0.0 or downloadable from the Elgg community site)
