### ISSUE TITLE
Elgg 4 supported version

### ISSUE THREAD

**Issue by rohit1290** [iionly/tidypics#56]
Hey, I know you love to make the updates on your own but I took the liberty to update the plugin to support 4.x.

Link: https://github.com/rohit1290/tidypics

If you want you can use this code as base.

Happy New Year!

**Comment by iionly** [comment]
Fully working release for Elgg 4 available at https://github.com/iionly/tidypics/releases/tag/4.0.0 or the Elgg community site.
