### ISSUE TITLE
Tidypics for elgg 5x ?

### ISSUE THREAD

**Issue by yurtseverfazli** [iionly/tidypics#59]
Do you plan to make tidypics for elgg 5x ?

**Comment by iionly** [comment]
Yes.

But I can't give any timeline / release date about it yet. I still have other plugins not even updated to Elgg 4 (and Elgg 3!) and it gets more complex trying to work on different plugins on different versions of Elgg in parallel. My main priority is getting all my plugins updated to Elgg 4.3. And any other work (for Elgg 5) would only happen in the foreseeable future if I have suddenly a lot more spare time than expected.

**Comment by iionly** [comment]
Fixed with release 5.0.0.
