### ISSUE TITLE
Issue with profile page on activation

### ISSUE THREAD

**Issue by Generative-Gaming** [iionly/tidypics#60]
Ok, so i really want to use this plugin but when i activate it, for some reason the profile pages of all users shows "This page isnt working" on chrome and other messages on other browsers. I think this has something to do with a widget but im not sure. Any fix for this?

**Comment by Generative-Gaming** [comment]
This happens when using the "photo albums" widget....

**Comment by iionly** [comment]
Which version of Elgg do you use and which version of PHP?

**Comment by Generative-Gaming** [comment]
5.1 Elgg and 8.1 PHP (I changed the 7.4 to 8.1 to test it out.... I'm
guessing it's not working for them yet. It seems to install fine and load
the settings but as soon as you add the widget thats the only issue with it
by the look of it. Hopefully a release for these versions will come out
soon as I really need this plugin

**Comment by iionly** [comment]
I've not yet updated Tidypics for Elgg 5. So, that is probably the reason why is fails to work. I can't say when I will be able to update it. Maybe I can take a look soon if it might not be that much to fix. But no promise.

**Comment by Generative-Gaming** [comment]
Yeah it just seems like an issue when installing the widget. I am going to
take a look at it later too and add some debugging to the widget, if I
manage to get it working I will reply here with Google drive link so you
can upload a working Elgg 5 patch. I got plenty of spare time now so I
don't mind having a look at it for ya

**Comment by iionly** [comment]
Fixed with release 5.0.0.
