### ISSUE TITLE
Error while opening "Mine" and "Friends" links from siteimageall page

### ISSUE THREAD

**Issue by rohit1290** [iionly/tidypics#61]
get_entity(): Argument #1 ($guid) must be of type int, string given, called in /home/xxx/public_html/mod/tidypics/views/default/resources/tidypics/lists/siteimagesowner.php on line 11

Elgg version: 5.1.5
Tidypic version: 5.0.0

How to reproduce the error: 
1. Visit https://site.com/photos/siteimagesall
2. Click on "Mine" option from the elgg menu filter.
3. The same error occurs when clicked on "Friends" option from the elgg menu filter.

**Comment by iionly** [comment]
Thanks for reporting. Fixed in version 5.0.1.
